// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlek3VVEPI7cAFDR-CgUopINt0yAIqAxE',
    appId: '1:679679396350:web:e587fa105758a1d64298af',
    messagingSenderId: '679679396350',
    projectId: 'stepquest-6f142',
    authDomain: 'stepquest-6f142.firebaseapp.com',
    storageBucket: 'stepquest-6f142.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfyjjHkdDMJxRZIxuDX-0kdhVtku_Tpuc',
    appId: '1:679679396350:android:3741299fd52c5c6c4298af',
    messagingSenderId: '679679396350',
    projectId: 'stepquest-6f142',
    storageBucket: 'stepquest-6f142.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPYKyJ1puP_4ZURlRez2Be05HHEiJLBgM',
    appId: '1:679679396350:ios:2b2ae04b8e73a9094298af',
    messagingSenderId: '679679396350',
    projectId: 'stepquest-6f142',
    storageBucket: 'stepquest-6f142.firebasestorage.app',
    iosBundleId: 'com.example.stepquestFitnessRpg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPYKyJ1puP_4ZURlRez2Be05HHEiJLBgM',
    appId: '1:679679396350:ios:2b2ae04b8e73a9094298af',
    messagingSenderId: '679679396350',
    projectId: 'stepquest-6f142',
    storageBucket: 'stepquest-6f142.firebasestorage.app',
    iosBundleId: 'com.example.stepquestFitnessRpg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlek3VVEPI7cAFDR-CgUopINt0yAIqAxE',
    appId: '1:679679396350:web:f5d7bba33674c7074298af',
    messagingSenderId: '679679396350',
    projectId: 'stepquest-6f142',
    authDomain: 'stepquest-6f142.firebaseapp.com',
    storageBucket: 'stepquest-6f142.firebasestorage.app',
  );
}
